### ISSUE TITLE
CardSet copy() metode jādod Card kopijas nevis oriģinālie objekti

### ISSUE THREAD

**Issue by Passiday** [Passiday/OOP-Cards#15]
@sakars pašreizējā CardSet copy() implementācija iedod oriģinālo card objektu array otra seta pagatavošanai, un šie objekti tur arī tiek izmantoti, līdz ar to kopijā reāli ir references uz tiem pašiem card objektiem. Tā nav vēlamā funkcionalitāte, tur vajadzētu dot iekšā map-otu array ar card.copy().

**Comment by Passiday** [comment]
ah, nu īsāk tur ir jādod iekšā cardSet.asArray()

**Comment by sakars** [comment]
jā izveidoju branch kad uztaisišu pielikšu pull request
