### ISSUE TITLE
CukasGame has a Java constructor

### ISSUE THREAD

**Issue by CodedSakura** [Passiday/OOP-Cards#17]
a constructor in JS is defined with `constructor() {}` not `$ClassName() {}`

#blame @towergame

**Comment by towergame** [comment]
**java**script doe

**Comment by sakars** [comment]
xd

**Comment by sakars** [comment]
#blame @towergame

**Comment by CodedSakura** [comment]
> **java**script doe

**car**pet

**Comment by towergame** [comment]
Anyways, resolved this in #18.

**Comment by sakars** [comment]
@towergame good
